// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use the direct (non-pooled) URL for migrations so that DDL statements
    // work correctly — pgBouncer in transaction mode doesn't support them.
    // On Neon: set DATABASE_URL_UNPOOLED to the direct connection string and
    // DATABASE_URL to the pooler string. Locally both can be the same.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
